version: 2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &build-packages
    run:
      name: Build
      command: npm run build

jobs:
  build:
    working_directory: ~/nestjs-multer-extended
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Code formatting
          command: npm run format
      - run:
          name: Code Linting
          command: npm run lint:fix
      - run:
          name: Build
          command: npm run build

  unit_tests:
    working_directory: ~/nestjs-multer-extended
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Unit tests
          command: npm run test

  integration_tests:
    working_directory: ~/nestjs-multer-extended
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Integration tests
          command: npm run test:integration
      - run:
          name: Collect coverage
          command: npm run coverage
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - integration_tests:
          requires:
            - build
