export const MULTER_MODULE_OPTIONS = 'MULTER_MODULE_OPTIONS';
export const MULTER_EXTENDED_S3_OPTIONS = 'MULTER_EXTENDED_S3_OPTIONS';
export const MULTER_EXTENDED_S3_MODULE_ID = 'MULTER_EXTENDED_S3_MODULE_ID';
